
<html>
<body>
<head><title>datos del cliente</title>
</head>
<fore METHOD = POST ACTION = "Validad.php">
<h4>INGRESE LOS SIGUIENTES DATOS DEL CLIENTE<H4><BR>
ID......<INPUT TYPE = text name = "id" size = "4"><br>
USUARIO..<INPUT TYPE = text name =  "usuario" size = "15"><br>
PASSWORD..<INPUT TYPE= text name = "password" size = "15"><br>

<?php
include("conexion.php");
$link=conectarse();



<br>

<p>input type = submit value = "INGRESAR">
<BR> <BR>




